#!/usr/bin/python
# -*- coding: UTF-8 -*-
"""
@author:admin
@file:setting.py
@time:2022/12/30
"""

# ArcCSE
ARCCSE_PRE_RANK_EMB_LAYER = [1, -1] # ["cls", 1, -1, [1, -1]]
ARCCSE_PRE_RANK_USE_ARC_LOSS = True
ARCCSE_PRE_RANK_USE_TRI_LOSS = False
ARCCSE_PRE_RANK_USE_DCL_LOSS = False # Decouple Loss
ARCCSE_PRE_RANK_LOSS = "2n" # [n, 2n]
ARCCSE_PRE_RANK_LEARNING_RATE = 8e-5
ARCCSE_PRE_RANK_BATCH_SAMPLES = 64
ARCCSE_PRE_RANK_ENCODE_BATCH_SIZE = 128
ARCCSE_PRE_RANK_EPOCHS = 10 # 30
ARCCSE_PRE_RANK_MAX_LEN = 128
ARCCSE_PRE_RANK_THRESHOLD = 0.7
ARCCSE_PRE_RANK_SEARCH_METHOD = "hnsw" # [bm25, invert_index, hnsw, faiss]
ARCCSE_PRE_RANK_SEARCH_RETURN = 200